enum AuthExceptions {
    TOKEN_CREATE_ERROR = 'TOKEN_CREATE_ERROR',
    TOKEN_NOT_FOUND = 'TOKEN_NOT_FOUND',
    TOKEN_EXPIRED = 'TOKEN_EXPIRED',
    TOKEN_INVALID = 'TOKEN_INVALID',
    PASSWORD_NOT_UPDATED = 'PASSWORD_NOT_UPDATED',
    UNAUTHORIZED_USER = 'UNAUTHORIZED_USER',
}

export default AuthExceptions;
