enum UserExceptions {
    NOT_FOUND = 'USER_NOT_FOUND',
    ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
    WRONG_PASSWORD = 'WRONG_PASSWORD',
    EMAIL_REQUIRED = 'EMAIL_REQUIRED',
    FAILED_UPDATE_BASIC_DATA = 'FAILED_UPDATE_BASIC_DATA',
}

export default UserExceptions;
